### PR TITLE
Feature/ng 8 demo

### PR DESCRIPTION
**Pull request by emclaug2**
#### Changes proposed in this Pull Request:
This addresses the "Mega Demo" item that I brought up in the retro today.  We can quickly see how our blue and blue-dark theme looks across all angular-material components.

This demo shows:
@pxblue/angular-components @ 3.0.0
@pxblue/angular-themes @ 5.1.2
@angular/material @ ^8.0.0

When we migrate between major versions of angular (from 8 to 10 for example), we could tag this project `angular-8-demo` to help archive which version of our dependencies worked with angular 8.  Or perhaps just use different branches, 1 per major version of angular. 

#### Screenshots:
image

### CODE REVIEW

**Comment by emclaug2** [comment]
Is this something that you think would provide value when developing/adjusting themes?

I would like to see this same demo running angular 9, angular 10 in different branches to test theme & component compatibility.

**Comment by emclaug2** [comment]
These demos were just aggregated from the angular material v8 component docs, copy/pasted with minor edits.

**Comment by huayunh** [comment]
I think this is awesome, and the format you are having it is great!

**Comment by joebochill** [comment]
I think this is a great step in the right direction. We have a story on the backlog to beef up these examples (and organize all of the stuff we want to show) and having variations for each major version of Angular will be a great testing tool. 

The original theme demo set out to show most of the Mat components 'in-context' of how they would be used, but I like the idea of a shotgun blast page too for a quick eyeball of everything.

**Comment by emclaug2** [comment]
All issues with this showcase should be fixed now.   Hosted here: https://pxblue-temp.web.app/

**Comment by joebochill** [comment]
Looking good. 

I would like to split the current "dashboard" into several separate views and beef them up a little. You can add all of these subpages as nested items under "In Context" (that way we can continue to test nested items with theme changes, etc.)
    - Dashboard (grid of scorecards with varying statuses)
    - Timeline
        image
    - Device Details
        image


Also, I didn't see table covered anywhere. Make sure you go through the angular material components and ensure that we have each one covered:
image

**Comment by joebochill** [comment]
For the device details, I was thinking something laid out like that with the cards (you don't have to integrate any actual charts)

**Comment by emclaug2** [comment]
@joebochill I think we can hold off on a settings page for now and add it as part of the CLI template work.  

I don't think the settings page in the original theme demo even shows any of our components.

**Comment by emclaug2** [comment]
Once this gets approved I can start testing out the components in ng v10.

**Review by joebochill — APPROVED** [review]
I will approve for the sake of moving ahead with the Angular 10 stuff, which is more important than angular 8.

I still think there is some work to clean up these examples / templates, but would rather not bog down on fixing things like that right now.

Since we will likely be coming back to these and making changes more often than we would for, say, a component library, i think it would be good to make branches (release?) for each major version of angular so we can easily come back and push changes to them as needed.

**Comment by emclaug2** [comment]
> I will approve for the sake of moving ahead with the Angular 10 stuff, which is more important than angular 8.
> 
> I still think there is some work to clean up these examples / templates, but would rather not bog down on fixing things like that right now.
> 
> Since we will likely be coming back to these and making changes more often than we would for, say, a component library, i think it would be good to make branches (release?) for each major version of angular so we can easily come back and push changes to them as needed.

I think it'll be more realistic to keep the actively maintained version of the component demo up to date with new screens & components but you're right, I'm going to make a branch angular 8 demo.

**Comment by joebochill** [comment]
> I think it'll be more realistic to keep the actively maintained version of the component demo up to date with new screens & components but you're right, I'm going to make tag dev `ng8` so we can come back to this demo if needed.

Agreed, the dev/master branch will be the primary focus. I just want us to have a convenient way of coming back to the older versions so we can test things out (e.g., if an adopter using angular 8 has some problem with a component). Tags will probably be fine for this if we don't plan to actively make updates to the older version examples and just use them for testing as-is.

**Comment by emclaug2** [comment]
> > I think it'll be more realistic to keep the actively maintained version of the component demo up to date with new screens & components but you're right, I'm going to make tag dev `ng8` so we can come back to this demo if needed.
> 
> Agreed, the dev/master branch will be the primary focus. I just want us to have a convenient way of coming back to the older versions so we can test things out (e.g., if an adopter using angular 8 has some problem with a component). Tags will probably be fine for this if we don't plan to actively make updates to the older version examples and just use them for testing as-is.

I ended up using branches because I agree that we will be updating this demo more often than the angular 8 version of our component library.  I made a release branch called `release/angular-8-demo` so we can come back and update this demo pretty easily.

**Pull request merged**
