### PR TITLE
Feature/match react

### PR DESCRIPTION
**Pull request by emclaug2**
#### Changes proposed in this Pull Request:
- Update angular showcase demo to match react.  It doesn't match 1-to-1 because there are a handful of components and variants that Angular Material does not support.  
- Hosted here: https://pxb-angular-theme-demo.web.app/

Angular Material does not support:
- Avatar
- Badge overlap
- Dot Badge Variant
- Outlined Chips
- Progress Indicator Labels
- Outlined Button Groups
- Outlined Button Group 'primary' | 'accent' color directive
- Text Button Group
- Date Picker Dialog
- Breadcrumbs
- Bottom Navigation
- Link Component

### CODE REVIEW

**Comment by daileytj** [comment]
Screen Shot 2021-08-11 at 3 12 34 PM

**Comment by daileytj** [comment]
Screen Shot 2021-08-11 at 3 16 04 PM
Can you make the stepper card wider when there is room for it so that the horizontal example can have multiple steps while still fitting on the screen

**Comment by daileytj** [comment]
Screen Shot 2021-08-11 at 3 16 53 PM

When the drawer nav items have the same name, both are "selected"

**Comment by daileytj** [comment]
Some things to consider...

- [ ]  Add icons to the drawer nav groups
- [ ] Use icons inside the fab button examples with labels instead of using the label inside the fab and letting the text overflow
- [ ] Add `flex: 1` to the material component > inputs > switch examples so they are spaced evenly
- [ ] Fix material components > inputs > outlined button ripple area (end up being oval instead of rounded). It would be nice if these looked more centered on the card as well.
- [ ] On refresh, the drawer state is no longer in sync (no item is "selected")
- [ ] The NonClickable chip is clickable
- [ ] Badge and chip examples could match better, but I realize some of those variants aren't achievable with angular material
- [ ] Would be cool if the pxblue components > display data > user menu > with custom colors example to use custom menu colors

**Comment by daileytj** [comment]
Screen Shot 2021-08-11 at 3 37 18 PM
overflow when RTL

**Comment by emclaug2** [comment]
> * [x]  The NonClickable chip is clickable

Fun fact here, I think this is a bug in angular material.  The below snippet is clickable: 
`<mat-chip [selectable]="false">NonClickable</mat-chip>`

I've modified it to ignore cursor events:
`<mat-chip [selectable]="false" style="pointer-events: none">NonClickable</mat-chip>`

**Comment by emclaug2** [comment]
> * [ ]  On refresh, the drawer state is no longer in sync (no item is "selected")

This is a little trickier; the Drawer NavItem does not respond to `expanded` onChange, so I've made a new issue for this.  The logic for having the Drawer set the correct active item & expand the correct group has been added but it'll only partially work until this bug is fixed:  https://github.com/pxblue/angular-component-library/issues/326

**Comment by daileytj** [comment]
> > * [x]   The NonClickable chip is clickable
> 
> Fun fact here, I think this is a bug in angular material. The below snippet is clickable:
> `<mat-chip [selectable]="false">NonClickable</mat-chip>`
> 
> I've modified it to ignore cursor events:
> `<mat-chip [selectable]="false" style="pointer-events: none">NonClickable</mat-chip>`

I think this may be better labeled as "non-selectable" or even omitted from the example set. The "selectable" input just modifies whether or not it can be selected, not if it can be clicked (you can disable the ripple, but it still has an elevation change on click). Also, if you add the selected state to the "warn" chip, it will show in red[500].

**Comment by daileytj** [comment]
Stepper update looks fine on desktop but needs to be responsive for mobile screen sizes.

**Comment by emclaug2** [comment]
> * [x]  Use icons inside the fab button examples with labels instead of using the label inside the fab and letting the text overflow

I've updated the FAB example to use icons, but ngMat doesn't support the `extended` fab property; just using some css to increase the width made it look weird so I took it out.

**Comment by emclaug2** [comment]
> I think this may be better labeled as "non-selectable" or even omitted from the example set. The "selectable" input just modifies whether or not it can be selected, not if it can be clicked (you can disable the ripple, but it still has an elevation change on click). Also, if you add the selected state to the "warn" chip, it will show in red[500].

I'm happy to take out this example.

**Comment by emclaug2** [comment]
> Screen Shot 2021-08-11 at 3 37 18 PM
> overflow when RTL
> and badge might need to be on the left when rtl??

For some reason I cannot get the `after` badgePosition to work; I think we may have to leave out the RTL behavior for the badge demo.  If this isn't fixed in the next version of angular I'll have to make an issue for it to figure out why it's non-responsive.

**Comment by daileytj** [comment]
- [ ] Make appbar 'sticky'
- [ ] Make the stepper look nice on mobile screen sizes
- [ ] Fix icon button ripple
- [ ] Set width on buttons so they are a uniform size
- [ ] Add padding/margin to the so that the last item/card on a given screen isn't touching the bottom when you scroll to the bottom

**Review by daileytj — APPROVED** [review]
Would be nice to get a second set of eyes on this just because it's such a large PR, but looks pretty good to me!

**Review by joebochill — APPROVED** [review]
Looks good to me...I only skimmed through the code but it seems to be in order.

**Comment by joebochill** [comment]
I think if there is anything wrong that we find, I'm happy to cover that in the Issues

**Pull request merged**
